import { Box, Typography } from '@mui/material';
import { renderers } from 'app/shared-components/htmlStyle/htmlStyle';
import { selectUserLanguage } from 'app/store/app/mainSlice';
import { selectProtectionData, setProtectionData } from 'app/store/app/pageSlice';
import { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { useDispatch, useSelector } from 'react-redux';
import ErrorPage from '../general/ErrorPage';
import LoadingPage from '../general/LoadingPage';

function Datenschutz() {
  const dispatch = useDispatch();
  const userLanguage = useSelector(selectUserLanguage);

  const protectionData = useSelector((state) => selectProtectionData(state, userLanguage));
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (protectionData) {
      setLoading(false);
      setError(null);
      return;
    }

    setLoading(true);
    setError(null);

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 1);

    fetch(`http://localhost/plainkit-main/api/dataProtection?lang=${userLanguage}`, { signal: controller.signal })
      .then((response) => {
        if (!response.ok) {
          throw new Error(`Network response was not ok, status: ${response.status}`);
        }
        return response.json();
      })
      .then((data) => {
        dispatch(setProtectionData({ userLanguage, data }));
      })
      .catch((error) => {
        if (userLanguage === 'en') {
          const mockData = {
            title: 'Privacy Policy',
            text_blocks: [
              '***1. An overview of data protection***',
              '**General information**\n\nThe following information will provide you with an easy to navigate overview of what will happen with your personal data when you visit our website. The term \u201cpersonal data\u201d comprises all data that can be used to personally identify you. For detailed information about the subject matter of data protection, please consult our Data Protection Declaration, which we have included beneath this copy.',
              '***2. Data recording on our website***',
              '**Who is the responsible party for the recording of data on this website (i.e. the \u201ccontroller\u201d)?**\n\nThe data on this website is processed by the operator of the website, whose contact information is available under section \u201cInformation Required by Law\u201d on this website.',
              '**How do we record your data?**\n\nWe collect your data as a result of your sharing of your data with us. This may, for instance be information you enter into our contact form. Our IT systems automatically record other data when you visit our website. This data comprises primarily technical information (e.g. web browser, operating system or time the site was accessed). This information is recorded automatically when you access our website.',
              '**What are the purposes we use your data for?**\n\nA portion of the information is generated to guarantee the error free provision of the website. Other data may be used to analyse your user patterns.',
              '**What rights do you have as far as your information is concerned?**\n\nYou have the right to receive information about the source, recipients and purposes of your archived personal data at any time without having to pay a fee for such disclosures. You also have the right to demand that your data are rectified, blocked or eradicated. Please do not hesitate to contact us at any time under the address disclosed in section \u201cInformation Required by Law\u201d on this website if you have questions about this or any other data protection related issues. You also have the right to log a complaint with the competent supervising agency. Moreover, under certain circumstances, you have the right to demand the restriction of the processing of your personal data. For details, please consult the Data Protection Declaration under section \u201cRight to Restriction of Data Processing.\u201d',
              '***3. General information and mandatory information***',
              '**Data protection**\n\nThe operators of this website and its pages take the protection of your personal data very seriously. Hence, we handle your personal data as confidential information and in compliance with the statutory data protection regulations and this Data Protection Declaration. Whenever you use this website, a variety of personal information will be collected. Personal data comprises data that can be used to personally identify you. This Data Protection Declaration explains which data we collect as well as the purposes we use this data for. It also explains how, and for which purpose the information is collected. We herewith advise you that the transmission of data via the Internet (i.e. through e-mail communications) may be prone to security gaps. It is not possible to completely protect data against third party access.',
              '**Information about the responsible party (referred to as the \u201ccontroller\u201d in the GDPR)**\n\nThe data processing controller on this website is:\n\nContemporary Dance School Hamburg GmbH\n\nStresemannstra\u00dfe 374 (Eingang B)\n\n22761 Hamburg\n\nPhone: +49 40 41924560\n\nE-mail: info@cdsh.de\n\nThe controller is the natural person or legal entity that single-handedly or jointly with others makes decisions as to the purposes of and resources for the processing of personal data (e.g. names, e-mail addresses, etc.).',
              '**Revocation of your consent to the processing of data**\n\nA wide range of data processing transactions are possible only subject to your express consent. You can also revoke at any time any consent you have already given us. To do so, all you are required to do is sent us an informal notification via e-mail. This shall be without prejudice to the lawfulness of any data collection that occurred prior to your revocation.',
              '**Right to object to the collection of data in special cases; right to object to direct advertising (Art. 21 GDPR)\nIn the event that data are processed on the basis of Art. 6 Sect. 1 lit. e or f GDPR, you have the right to at any time object to the processing of your personal data based on grounds arising from your unique situation. This also applies to any profiling based on these provisions. To determine the legal basis, on which any processing of data is based, please consult this Data Protection Declaration. If you log an objection, we will no longer process your affected personal data, unless we are in a position to present compelling protection worthy grounds for the processing of your data, that outweigh your interests, rights and freedoms or if the purpose of the processing is the claiming, exercising or defence of legal entitlements (objection pursuant to Art. 21 Sect. 1 GDPR). If your personal data is being processed in order to engage in direct advertising, you have the right to at any time object to the processing of your affected personal data for the purposes of such advertising. This also applies to profiling to the extent that it is affiliated with such direct advertising. If you object, your personal data will subsequently no longer be used for direct advertising purposes (objection pursuant to Art. 21 Sect. 2 GDPR).**',
              '**Right to log a complaint with the competent supervisory agency**\n\nIn the event of violations of the GDPR, data subjects are entitled to log a complaint with a supervisory agency, in particular in the member state where they usually maintain their domicile, place of work or at the place where the alleged violation occurred. The right to log a complaint is in effect regardless of any other administrative or court proceedings available as legal recourses.',
              '**Right to data portability**\n\nYou have the right to demand that we hand over any data we automatically process on the basis of your consent or in order to fulfil a contract be handed over to you or a third party in a commonly used, machine readable format. If you should demand the direct transfer of the data to another controller, this will be done only if it is technically feasible.',
              '**SSL and/or TLS encryption**\n\nFor security reasons and to protect the transmission of confidential content, such as purchase orders or inquiries you submit to us as the website operator, this website uses either an SSL or a TLS encryption programme. You can recognise an encrypted connection by checking whether the address line of the browser switches from \u201chttp://\u201d to \u201chttps://\u201d and also by the appearance of the lock icon in the browser line. If the SSL or TLS encryption is activated, data you transmit to us cannot be read by third parties.',
              '**Information about, blockage, rectification and eradication of data**\n\nWithin the scope of the applicable statutory provisions, you have the right to at any time demand information about your archived personal data, their source and recipients as well as the purpose of the processing of your data. You may also have a right to have your data rectified, blocked or eradicated. If you have questions about this subject matter or any other questions about personal data, please do not hesitate to contact us at any time at the address provided in section \u201cInformation Required by Law.\u201d',
              '**Right to demand processing restrictions**\n\nYou have the right to demand the imposition of restrictions as far as the processing of your personal data is concerned. To do so, you may contact us at any time at the address provided in section \u201cInformation Required by Law.\u201d The right to demand restriction of processing applies in the following cases:\n\n- In the event that you should dispute the correctness of your data archived by us, we will usually need some time to verify this claim. During the time that this investigation is ongoing, you have the right to demand that we restrict the processing of your personal data.\n- If the processing of your personal data was/is conducted in an unlawful manner, you have the option to demand the restriction of the processing of your data in lieu of demanding the eradication of this data.\n- If we do not need your personal data any longer and you need it to exercise, defend or claim legal entitlements, you have the right to demand the restriction of the processing of your personal data instead of its eradication.\n- If you have raised an objection pursuant to Art. 21 Sect. 1 GDPR, your rights and our rights will have to be weighed against each other. As long as it has not been determined whose interests prevail, you have the right to demand a restriction of the processing of your personal data.\n- If you have restricted the processing of your personal data, these data \u2013 with the exception of their archiving \u2013 may be processed only subject to your consent or to claim, exercise or defend legal entitlements or to protect the rights of other natural persons or legal entities or for important public interest reasons cited by the European Union or a member state of the EU.',
              '**Rejection of unsolicited e-mails**\n\nWe herewith object to the use of contact information published in conjunction with the mandatory information to be provided in section \u201cInformation Required by Law\u201d to send us promotional and information material that we have not expressly requested. The operators of this website and its pages reserve the express right to take legal action in the event of the unsolicited sending of promotional information, for instance via SPAM messages.',
              '***4. Recording of data on our website***',
              '**Cookies**\n\nIn some instances, our website and its pages use so-called cookies. Cookies do not cause any damage to your computer and do not contain viruses. The purpose of cookies is to make our website more user friendly, effective and more secure. Cookies are small text files that are placed on your computer and stored by your browser. Most of the cookies we use are so-called \u201csession cookies.\u201d They are automatically deleted after your leave our site. Other cookies will remain archived on your device until you delete them. These cookies enable us to recognise your browser the next time you visit our website. You can adjust the settings of your browser to make sure that you are notified every time cookies are placed and to enable you to accept cookies only in specific cases or to exclude the acceptance of cookies for specific situations or in general and to activate the automatic deletion of cookies when you close your browser. If you deactivate cookies, the functions of this website may be limited. Cookies that are required for the performance of the electronic communications transaction or to provide certain functions you want to use (e.g. the shopping cart function), are stored on the basis of Art. 6 Sect. 1 lit. f GDPR. The website operator has a legitimate interest in storing cookies to ensure the technically error free and optimised provision of the operator\u2019s services. If other cookies (e.g. cookies for the analysis of your browsing patterns) should be stored, they are addressed separately in this Data Protection Declaration.',
              '**Server log files**\n\nThe provider of this website and its pages automatically collects and stores information in so-called server log files, which your browser communicates to us automatically. The information comprises:\n\n- The type and version of browser used\n- The used operating system\n- Referrer URL\n- The hostname of the accessing computer\n- The time of the server inquiry\n- The IP address\n\nThis data is not merged with other data sources. This data is recorded on the basis of Art. 6 Sect. 1 lit. f GDPR. The operator of the website has a legitimate interest in the technically error free depiction and the optimization of the operator\u2019s website. In order to achieve this, server log files must be recorded.',
              '**Contact form**\n\nIf you submit inquiries to us via our contact form, the information provided in the contact form as well as any contact information provided therein will be stored by us in order to handle your inquiry and in the event that we have further questions. We will not share this information without your consent.\n\nHence, the processing of the data entered into the contact form occurs exclusively based on your consent (Art. 6 Sect. 1 lit. a GDPR). You have the right to revoke at any time any consent you have already given us. To do so, all you are required to do is sent us an informal notification via e-mail. This shall be without prejudice to the lawfulness of any data collection that occurred prior to your revocation.\n\nThe information you have entered into the contact form shall remain with us until you ask us to eradicate the data, revoke your consent to the archiving of data or if the purpose for which the information is being archived no longer exists (e.g. after we have concluded our response to your inquiry). This shall be without prejudice to any mandatory legal provisions \u2013 in particular retention periods.',
              '**Request by e-mail, telephone or fax**\n\nIf you contact us by e-mail, telephone or fax, your request, including all resulting personal data (name, request) will be stored and processed by us for the purpose of processing your request. We do not pass these data on without your consent. The processing of these data is based on Art. 6 para. 1 lit. b GDPR, if your request is related to the execution of a contract or if it is necessary to carry out pre-contractual measures. In all other cases, the processing is based on your consent (Article 6 (1) a GDPR) and/or on our legitimate interests (Article 6 (1) (f) GDPR), since we have a legitimate interest in the effective processing of requests addressed to us. The data sent by you to us via contact requests remain with us until you request us to delete, revoke your consent to the storage or the purpose for the data storage lapses (e.g. after completion of your request). Mandatory statutory provisions \u2013 in particular statutory retention periods \u2013 remain unaffected.',
              '**Processing of data (customer and contract data)**\n\nWe collect, process and use personal data only to the extent necessary for the establishment, content organization or change of the legal relationship (data inventory). These actions are taken on the basis of Art. 6 Sect. 1 lit. b GDPR, which permits the processing of data for the fulfilment of a contract or pre-contractual actions. We collect, process and use personal data concerning the use of our website (usage data) only to the extent that this is necessary to make it possible for users to utilize the services and to bill for them. The collected customer data shall be eradicated upon completion of the order or the termination of the business relationship. This shall be without prejudice to any statutory retention mandates.',
              '***5. Social media***',
              '**Facebook plug-ins (Like & Share button)**\n\nWe have integrated plug-ins of the social network Facebook, provided by Facebook Inc., 1 Hacker Way, Menlo Park, California 94025, USA, on our website. You will be able to recognise Facebook plug-ins by the Facebook logo or the \u201cLike\u201d button on our website. An overview of the Facebook plug-ins is available under the following link: https://developers.facebook.com/docs/plugins/.\n\nWhenever you visit our website and its pages, the plug-in will establish a direct connection between your browser and the Facebook server. As a result, Facebook will receive the information that you have visited our website with your plug-in. However, if you click the Facebook \u201cLike\u201d button while you are logged into your Facebook account, you can link the content of our website and its pages with your Facebook profile. As a result, Facebook will be able to allocate the visit to our website and its pages to your Facebook user account. We have to point out, that we as the provider of the website do not have any knowledge of the transferred data and its use by Facebook. For more detailed information, please consult the Data Privacy Declaration of Facebook at: https://www.facebook.com/privacy/explanation. If you do not want Facebook to be able to allocate your visit to our website and its pages to your Facebook user account, please log out of your Facebook account while you are on our website. The use of the Facebook plug-in is based on Art. 6 Sect. 1 lit. f GDPR. The operator of the website has a legitimate interest in being as visible as possible on social media.',
              '***6. Newsletter***',
              '**Newsletter data**\n\nIf you would like to subscribe to the newsletter offered on this website, we will need from you an e-mail address as well as information that allow us to verify that you are the owner of the e-mail address provided and consent to the receipt of the newsletter. No further data shall be collected or shall be collected only on a voluntary basis. We shall use such data only for the sending of the requested information and shall not share such data with any third parties.\n\nThe processing of the information entered into the newsletter subscription form shall occur exclusively on the basis of your consent (Art. 6 Sect. 1 lit. a GDPR). You may revoke the consent you have given to the archiving of data, the e-mail address and the use of this information for the sending of the newsletter at any time, for instance by clicking on the \u201cUnsubscribe\u201d link in the newsletter. This shall be without prejudice to the lawfulness of any data processing transactions that have taken place to date.\n\nThe data you archive with us for the purpose of the newsletter subscription shall be archived by us until you unsubscribe from the newsletter. Once you cancel your subscription to the newsletter, the data shall be deleted. This shall not affect data we have been archiving for other purposes.',
              '***7. Plug-ins and Tools***',
              '**Vimeo**\n\nOur website uses plug-ins of the video portal Vimeo. The provider is Vimeo Inc., 555 West 18th Street, New York, New York 10011, USA. If you visit one of the pages on our website into which a Vimeo plug-in has been integrated, a connection to Vimeo\u2019s servers will be established. As a consequence, the Vimeo server will receive information as to which of our pages you have visited. Moreover, Vimeo will receive your IP address. This will also happen if you are not logged into Vimeo or do not have an account with Vimeo. The information recorded by Vimeo will be transmitted to Vimeo\u2019s server in the United States. If you are logged into your Vimeo account, you enable Vimeo to directly allocate your browsing patterns to your personal profile. You can prevent this by logging out of your Vimeo account. The use of Vimeo is based on our interest in presenting our online content in an appealing manner. Pursuant to Art. 6 Sect. 1 lit. f GDPR, this is a legitimate interest. For more information on how Vimeo handles user data, please consult the Vimeo Data Privacy Policy under: https://vimeo.com/privacy.',
              '***8. Custom Services***',
              '**Applications / Auditions**\n\nWe offer website visitors the opportunity to submit job applications to us (e.g. via e-mail, via postal services on by submitting the online job application form). Below, we will brief you on the scope, purpose and use of the personal data collected from you in conjunction with the application process. We assure you that the collection, processing and use of your data will occur in compliance with the applicable data privacy rights and all other statutory provisions and that your data will always be treated as strictly confidential.',
              '\u2014 Scope and purpose of the collection of data\n\nIf you submit a job application to us, we will process any affiliated personal data (e.g. contact and communications data, application documents, notes taken during job interviews, etc.), if they are required to make a decision concerning the establishment or an employment relationship. The legal grounds for the aforementioned are \u00a7 26 New GDPR according to German Law (Negotiation of an Employment Relationship), Art. 6 Sect. 1 lit. b GDPR (General Contract Negotiations) and \u2013 provided you have given us your consent \u2013 Art. 6 Sect. 1 lit. a GDPR. You may revoke any consent given at any time. Within our company, your personal data will only be shared with individuals who are involved in the processing of your job application. If your job application should result in your recruitment, the data you have submitted will be archived on the grounds of \u00a7 26 New GDPR and Art. 6 Sect. 1 lit. b GDPR for the purpose of implementing the employment relationship in our data processing system.',
              '\u2014 Data Archiving Period\n\nIf we should not be able to offer you a position, if you refuse a job offer, retract your application, revoke your consent to the processing of your data or ask us to delete your data, we will store your transferred data, incl. any physically submitted application documents for a maximum of 6 months after the conclusion of the application process (retention period) to enable us to track the details of the application process in the event of disparities (Art. 6 Sect. 1 lit. f GDPR).',
              'YOU HAVE THE OPTION TO OBJECT TO THIS STORAGE/RETENTION OF YOUR DATA IF YOU HAVE LEGITIMATE INTERESTS TO DO SO THAT OUTWEIGH OUR INTERESTS.',
              'Once the retention period has expired, the data will be deleted, unless we are subject to any other statutory retention obligations or if any other legal grounds exist to continue to store the data. If it should be foreseeable that the retention of your data will be necessary after the retention period has expired (e.g. due to imminent or pending litigation), the data shall not be deleted until the data have become irrelevant. This shall be without prejudice to any other statutory retention periods.',
            ],
          };
          dispatch(setProtectionData({ userLanguage, data: mockData }));
        } else {
          const mockData = {
            title: 'Datenschutz',
            text_blocks: [
              '***1. Datenschutz auf einen Blick***',
              '**Allgemeine Hinweise**\n\nDie folgenden Hinweise geben einen einfachen \u00dcberblick dar\u00fcber, was mit Ihren personenbezogenen Daten passiert, wenn Sie unsere Website besuchen. Personenbezogene Daten sind alle Daten, mit denen Sie pers\u00f6nlich identifiziert werden k\u00f6nnen. Ausf\u00fchrliche Informationen zum Thema Datenschutz entnehmen Sie unserer unter diesem Text aufgef\u00fchrten Datenschutzerkl\u00e4rung.',
              '***2. Datenerfassung auf unserer Website***',
              '**Wer ist verantwortlich f\u00fcr die Datenerfassung auf dieser Website?**\n\nDie Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber. Dessen Kontaktdaten k\u00f6nnen Sie dem Impressum dieser Website entnehmen.',
              '**Wie erfassen wir Ihre Daten?**\n\nIhre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich z.B. um Daten handeln, die Sie in ein Kontaktformular eingeben. Andere Daten werden automatisch beim Besuch der Website durch unsere IT-Systeme erfasst. Das sind vor allem technische Daten (z.B. Internetbrowser, Betriebssystem oder Uhrzeit des Seitenaufrufs). Die Erfassung dieser Daten erfolgt automatisch, sobald Sie unsere Website betreten.',
              '**Wof\u00fcr nutzen wir Ihre Daten?**\n\nEin Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gew\u00e4hrleisten. Andere Daten k\u00f6nnen zur Analyse Ihres Nutzerverhaltens verwendet werden.',
              '**Welche Rechte haben Sie bez\u00fcglich Ihrer Daten?**\n\nSie haben jederzeit das Recht unentgeltlich Auskunft \u00fcber Herkunft, Empf\u00e4nger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Sie haben au\u00dferdem ein Recht, die Berichtigung, Sperrung oder L\u00f6schung dieser Daten zu verlangen. Hierzu sowie zu weiteren Fragen zum Thema Datenschutz k\u00f6nnen Sie sich jederzeit unter der im Impressum angegebenen Adresse an uns wenden. Des Weiteren steht Ihnen ein Beschwerderecht bei der zust\u00e4ndigen Aufsichtsbeh\u00f6rde zu. Au\u00dferdem haben Sie das Recht, unter bestimmten Umst\u00e4nden die Einschr\u00e4nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Details hierzu entnehmen Sie der Datenschutzerkl\u00e4rung unter \u201eRecht auf Einschr\u00e4nkung der Verarbeitung\u201c.',
              '***3. Allgemeine Hinweise und Pflichtinformationen***',
              '**Datenschutz**\n\nDie Betreiber dieser Seiten nehmen den Schutz Ihrer pers\u00f6nlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerkl\u00e4rung. Wenn Sie diese Website benutzen, werden verschiedene personenbezogene Daten erhoben. Personenbezogene Daten sind Daten, mit denen Sie pers\u00f6nlich identifiziert werden k\u00f6nnen. Die vorliegende Datenschutzerkl\u00e4rung erl\u00e4utert, welche Daten wir erheben und wof\u00fcr wir sie nutzen. Sie erl\u00e4utert auch, wie und zu welchem Zweck das geschieht. Wir weisen darauf hin, dass die Daten\u00fcbertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitsl\u00fccken aufweisen kann. Ein l\u00fcckenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht m\u00f6glich.',
              '**Hinweis zur verantwortlichen Stelle**\n\nDie verantwortliche Stelle f\u00fcr die Datenverarbeitung auf dieser Website ist:\n\nContemporary Dance School Hamburg GmbH\n\nStresemannstra\u00dfe 374 (Eingang B)\n\n22761 Hamburg\n\nTelefon: +49 40 41924560\n\nE-Mail: info@cdsh.de\n\nVerantwortliche Stelle ist die nat\u00fcrliche oder juristische Person, die allein oder gemeinsam mit anderen \u00fcber die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten (z.B. Namen, E-Mail-Adressen o. \u00c4.) entscheidet.',
              '**Widerruf Ihrer Einwilligung zur Datenverarbeitung**\n\nViele Datenverarbeitungsvorg\u00e4nge sind nur mit Ihrer ausdr\u00fccklichen Einwilligung m\u00f6glich. Sie k\u00f6nnen eine bereits erteilte Einwilligung jederzeit widerrufen. Dazu reicht eine formlose Mitteilung per E-Mail an uns. Die Rechtm\u00e4\u00dfigkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom Widerruf unber\u00fchrt.',
              '**Widerspruchsrecht gegen die Datenerhebung in besonderen F\u00e4llen sowie gegen Direktwerbung (Art. 21 DSGVO)\nWenn die Datenverarbeitung auf Grundlage von Art. 6 Abs. 1 lit. e oder f DSGVO erfolgt, haben Sie jederzeit das Recht, aus Gr\u00fcnden, die sich aus Ihrer besonderen Situation ergeben, gegen die Verarbeitung Ihrer personenbezogenen Daten Widerspruch einzulegen; dies gilt auch f\u00fcr ein auf diese Bestimmungen gest\u00fctztes Profiling. Die jeweilige Rechtsgrundlage, auf denen eine Verarbeitung beruht, entnehmen Sie dieser Datenschutzerkl\u00e4rung. Wenn Sie Widerspruch einlegen, werden wir Ihre betroffenen personenbezogenen Daten nicht mehr verarbeiten, es sei denn, wir k\u00f6nnen zwingende schutzw\u00fcrdige Gr\u00fcnde f\u00fcr die Verarbeitung nachweisen, die Ihre Interessen, Rechte und Freiheiten \u00fcberwiegen oder die Verarbeitung dient der Geltendmachung, Aus\u00fcbung oder Verteidigung von Rechtsanspr\u00fcchen (Widerspruch nach Art. 21 Abs. 1 DSGVO).**\n\n**Werden Ihre personenbezogenen Daten verarbeitet, um Direktwerbung zu betreiben, so haben Sie das Recht, jederzeit Widerspruch gegen die Verarbeitung Sie betreffender personenbezogener Daten zum Zwecke derartiger Werbung einzulegen; dies gilt auch f\u00fcr das Profiling, soweit es mit solcher Direktwerbung in Verbindung steht. Wenn Sie widersprechen, werden Ihre personenbezogenen Daten anschlie\u00dfend nicht mehr zum Zwecke der Direktwerbung verwendet (Widerspruch nach Art. 21 Abs. 2 DSGVO).**',
              '**Beschwerderecht bei der zust\u00e4ndigen Aufsichtsbeh\u00f6rde**\n\nIm Falle von Verst\u00f6\u00dfen gegen die DSGVO steht den Betroffenen ein Beschwerderecht bei einer Aufsichtsbeh\u00f6rde, insbesondere in dem Mitgliedstaat ihres gew\u00f6hnlichen Aufenthalts, ihres Arbeitsplatzes oder des Orts des mutma\u00dflichen Versto\u00dfes zu. Das Beschwerderecht besteht unbeschadet anderweitiger verwaltungsrechtlicher oder gerichtlicher Rechtsbehelfe.',
              '**Recht auf Daten\u00fcbertragbarkeit**\n\nSie haben das Recht, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erf\u00fcllung eines Vertrags automatisiert verarbeiten, an sich oder an einen Dritten in einem g\u00e4ngigen, maschinenlesbaren Format aush\u00e4ndigen zu lassen. Sofern Sie die direkte \u00dcbertragung der Daten an einen anderen Verantwortlichen verlangen, erfolgt dies nur, soweit es technisch machbar ist.',
              '**SSL- bzw. TLS-Verschl\u00fcsselung**\n\nDiese Seite nutzt aus Sicherheitsgr\u00fcnden und zum Schutz der \u00dcbertragung vertraulicher Inhalte, wie zum Beispiel Bestellungen oder Anfragen, die Sie an uns als Seitenbetreiber senden, eine SSL-bzw. TLS-Verschl\u00fcsselung. Eine verschl\u00fcsselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers von \u201chttp://\u201d auf \u201chttps://\u201d wechselt und an dem Schloss-Symbol in Ihrer Browserzeile. Wenn die SSL- bzw. TLS-Verschl\u00fcsselung aktiviert ist, k\u00f6nnen die Daten, die Sie an uns \u00fcbermitteln, nicht von Dritten mitgelesen werden.',
              '**Auskunft, Sperrung, L\u00f6schung und Berichtigung**\n\nSie haben im Rahmen der geltenden gesetzlichen Bestimmungen jederzeit das Recht auf unentgeltliche Auskunft \u00fcber Ihre gespeicherten personenbezogenen Daten, deren Herkunft und Empf\u00e4nger und den Zweck der Datenverarbeitung und ggf. ein Recht auf Berichtigung, Sperrung oder L\u00f6schung dieser Daten. Hierzu sowie zu weiteren Fragen zum Thema personenbezogene Daten k\u00f6nnen Sie sich jederzeit unter der im Impressum angegebenen Adresse an uns wenden.',
              '**Recht auf Einschr\u00e4nkung der Verarbeitung**\n\nSie haben das Recht, die Einschr\u00e4nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Hierzu k\u00f6nnen Sie sich jederzeit unter der im Impressum angegebenen Adresse an uns wenden. Das Recht auf Einschr\u00e4nkung der Verarbeitung besteht in folgenden F\u00e4llen:\n\n- Wenn Sie die Richtigkeit Ihrer bei uns gespeicherten personenbezogenen Daten bestreiten, ben\u00f6tigen wir in der Regel Zeit, um dies zu \u00fcberpr\u00fcfen. F\u00fcr die Dauer der Pr\u00fcfung haben Sie das Recht, die Einschr\u00e4nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.\n- Wenn die Verarbeitung Ihrer personenbezogenen Daten unrechtm\u00e4\u00dfig geschah / geschieht, k\u00f6nnen Sie statt der L\u00f6schung die Einschr\u00e4nkung der Datenverarbeitung verlangen.\n- Wenn wir Ihre personenbezogenen Daten nicht mehr ben\u00f6tigen, Sie sie jedoch zur Aus\u00fcbung, Verteidigung oder Geltendmachung von Rechtsanspr\u00fcchen ben\u00f6tigen, haben Sie das Recht, statt der L\u00f6schung die Einschr\u00e4nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.\n- Wenn Sie einen Widerspruch nach Art. 21 Abs. 1 DSGVO eingelegt haben, muss eine Abw\u00e4gung zwischen Ihren und unseren Interessen vorgenommen werden. Solange noch nicht feststeht, wessen Interessen \u00fcberwiegen, haben Sie das Recht, die Einschr\u00e4nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.\n- Wenn Sie die Verarbeitung Ihrer personenbezogenen Daten eingeschr\u00e4nkt haben, d\u00fcrfen diese Daten \u2013 von ihrer Speicherung abgesehen \u2013 nur mit Ihrer Einwilligung oder zur Geltendmachung, Aus\u00fcbung oder Verteidigung von Rechtsanspr\u00fcchen oder zum Schutz der Rechte einer anderen nat\u00fcrlichen oder juristischen Person oder aus Gr\u00fcnden eines wichtigen \u00f6ffentlichen Interesses der Europ\u00e4ischen Union oder eines Mitgliedstaats verarbeitet werden.',
              '**Widerspruch gegen Werbe-E-Mails**\n\nDer Nutzung von im Rahmen der Impressumspflicht ver\u00f6ffentlichten Kontaktdaten zur \u00dcbersendung von nicht ausdr\u00fccklich angeforderter Werbung und Informationsmaterialien wird hiermit widersprochen. Die Betreiber der Seiten behalten sich ausdr\u00fccklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-E-Mails, vor.',
              '***4. Datenerfassung auf unserer Website***',
              '**Cookies**\n\nDie Internetseiten verwenden teilweise so genannte Cookies. Cookies richten auf Ihrem Rechner keinen Schaden an und enthalten keine Viren. Cookies dienen dazu, unser Angebot nutzerfreundlicher, effektiver und sicherer zu machen. Cookies sind kleine Textdateien, die auf Ihrem Rechner abgelegt werden und die Ihr Browser speichert. Die meisten der von uns verwendeten Cookies sind so genannte \u201cSession-Cookies\u201d. Sie werden nach Ende Ihres Besuchs automatisch gel\u00f6scht. Andere Cookies bleiben auf Ihrem Endger\u00e4t gespeichert bis Sie diese l\u00f6schen. Diese Cookies erm\u00f6glichen es uns, Ihren Browser beim n\u00e4chsten Besuch wiederzuerkennen. Sie k\u00f6nnen Ihren Browser so einstellen, dass Sie \u00fcber das Setzen von Cookies informiert werden und Cookies nur im Einzelfall erlauben, die Annahme von Cookies f\u00fcr bestimmte F\u00e4lle oder generell ausschlie\u00dfen sowie das automatische L\u00f6schen der Cookies beim Schlie\u00dfen des Browser aktivieren. Bei der Deaktivierung von Cookies kann die Funktionalit\u00e4t dieser Website eingeschr\u00e4nkt sein.\n\nCookies, die zur Durchf\u00fchrung des elektronischen Kommunikationsvorgangs oder zur Bereitstellung bestimmter, von Ihnen erw\u00fcnschter Funktionen (z.B. Warenkorbfunktion) erforderlich sind, werden auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO gespeichert. Der Websitebetreiber hat ein berechtigtes Interesse an der Speicherung von Cookies zur technisch fehlerfreien und optimierten Bereitstellung seiner Dienste. Soweit andere Cookies (z.B. Cookies zur Analyse Ihres Surfverhaltens) gespeichert werden, werden diese in dieser Datenschutzerkl\u00e4rung gesondert behandelt.',
              '**Server-Log-Dateien**:\n\nDer Provider der Seiten erhebt und speichert automatisch Informationen in so genannten Server-Log-Dateien, die Ihr Browser automatisch an uns \u00fcbermittelt. Dies sind:\n\n- Browsertyp und Browserversion\n- verwendetes Betriebssystem\n- Referrer URL\n- Hostname des zugreifenden Rechners\n- Uhrzeit der Serveranfrage\n- IP-Adresse\n\nEine Zusammenf\u00fchrung dieser Daten mit anderen Datenquellen wird nicht vorgenommen. Die Erfassung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Der Websitebetreiber hat ein berechtigtes Interesse an der technisch fehlerfreien Darstellung und der Optimierung seiner Website \u2013 hierzu m\u00fcssen die Server-Log-Files erfasst werden.',
              '**Kontaktformular**\n\nWenn Sie uns per Kontaktformular Anfragen zukommen lassen, werden Ihre Angaben aus dem Anfrageformular inklusive der von Ihnen dort angegebenen Kontaktdaten zwecks Bearbeitung der Anfrage und f\u00fcr den Fall von Anschlussfragen bei uns gespeichert. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter.\n\nDie Verarbeitung der in das Kontaktformular eingegebenen Daten erfolgt somit ausschlie\u00dflich auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO). Sie k\u00f6nnen diese Einwilligung jederzeit widerrufen. Dazu reicht eine formlose Mitteilung per E-Mail an uns. Die Rechtm\u00e4\u00dfigkeit der bis zum Widerruf erfolgten Datenverarbeitungsvorg\u00e4nge bleibt vom Widerruf unber\u00fchrt.\n\nDie von Ihnen im Kontaktformular eingegebenen Daten verbleiben bei uns, bis Sie uns zur L\u00f6schung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck f\u00fcr die Datenspeicherung entf\u00e4llt (z.B. nach abgeschlossener Bearbeitung Ihrer Anfrage). Zwingende gesetzliche Bestimmungen \u2013 insbesondere Aufbewahrungsfristen \u2013 bleiben unber\u00fchrt.',
              '**Anfrage per E-Mail, Telefon oder Telefax**\n\nWenn Sie uns per E-Mail, Telefon oder Telefax kontaktieren, wird Ihre Anfrage inklusive aller daraus hervorgehenden personenbezogenen Daten (Name, Anfrage) zum Zwecke der Bearbeitung Ihres Anliegens bei uns gespeichert und verarbeitet. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter.\n\nDie Verarbeitung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, sofern Ihre Anfrage mit der Erf\u00fcllung eines Vertrags zusammenh\u00e4ngt oder zur Durchf\u00fchrung vorvertraglicher Ma\u00dfnahmen erforderlich ist. In allen \u00fcbrigen F\u00e4llen beruht die Verarbeitung auf Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO) und / oder auf unseren berechtigten Interessen (Art. 6 Abs. 1 lit. f DSGVO), da wir ein berechtigtes Interesse an der effektiven Bearbeitung der an uns gerichteten Anfragen haben.\n\nDie von Ihnen an uns per Kontaktanfragen \u00fcbersandten Daten verbleiben bei uns, bis Sie uns zur L\u00f6schung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck f\u00fcr die Datenspeicherung entf\u00e4llt (z. B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen \u2013 insbesondere gesetzliche Aufbewahrungsfristen \u2013 bleiben unber\u00fchrt.',
              '**Verarbeiten von Daten (Kunden- und Vertragsdaten)**\n\nWir erheben, verarbeiten und nutzen personenbezogene Daten nur, soweit sie f\u00fcr die Begr\u00fcndung, inhaltliche Ausgestaltung oder \u00c4nderung des Rechtsverh\u00e4ltnisses erforderlich sind (Bestandsdaten). Dies erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, der die Verarbeitung von Daten zur Erf\u00fcllung eines Vertrags oder vorvertraglicher Ma\u00dfnahmen gestattet. Personenbezogene Daten \u00fcber die Inanspruchnahme unserer Internetseiten (Nutzungsdaten) erheben, verarbeiten und nutzen wir nur, soweit dies erforderlich ist, um dem Nutzer die Inanspruchnahme des Dienstes zu erm\u00f6glichen oder abzurechnen.\n\nDie erhobenen Kundendaten werden nach Abschluss des Auftrags oder Beendigung der Gesch\u00e4ftsbeziehung gel\u00f6scht. Gesetzliche Aufbewahrungsfristen bleiben unber\u00fchrt.',
              '***5. Soziale Medien***',
              '**Facebook-Plugins (Like & Share-Button)**\n\nAuf unseren Seiten sind Plugins des sozialen Netzwerks Facebook, Anbieter Facebook Inc., 1 Hacker Way, Menlo Park, California 94025, USA, integriert. Die Facebook-Plugins erkennen Sie an dem Facebook-Logo oder dem \u201eLike-Button\u201c (\u201eGef\u00e4llt mir\u201c) auf unserer Seite. Eine \u00dcbersicht \u00fcber die Facebook-Plugins finden Sie hier: https://developers.facebook.com/docs/plugins/?locale=de_DE.\n\nWenn Sie unsere Seiten besuchen, wird \u00fcber das Plugin eine direkte Verbindung zwischen Ihrem Browser und dem Facebook-Server hergestellt. Facebook erh\u00e4lt dadurch die Information, dass Sie mit Ihrer IP-Adresse unsere Seite besucht haben. Wenn Sie den Facebook \u201eLike-Button\u201c anklicken w\u00e4hrend Sie in Ihrem Facebook-Account eingeloggt sind, k\u00f6nnen Sie die Inhalte unserer Seiten auf Ihrem Facebook-Profil verlinken. Dadurch kann Facebook den Besuch unserer Seiten Ihrem Benutzerkonto zuordnen. Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der \u00fcbermittelten Daten sowie deren Nutzung durch Facebook erhalten. Weitere Informationen hierzu finden Sie in der Datenschutzerkl\u00e4rung von Facebook unter: https://de-de.facebook.com/privacy/explanation.\n\nWenn Sie nicht w\u00fcnschen, dass Facebook den Besuch unserer Seiten Ihrem Facebook-Nutzerkonto zuordnen kann, loggen Sie sich bitte aus Ihrem Facebook-Benutzerkonto aus.\n\nDie Verwendung der Facebook-Plugins erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Der Websitebetreiber hat ein berechtigtes Interesse an einer m\u00f6glichst umfangreichen Sichtbarkeit in den Sozialen Medien.',
              '***6. Newsletter***',
              '**Newsletterdaten**\n\nWenn Sie den auf der Website angebotenen Newsletter beziehen m\u00f6chten, ben\u00f6tigen wir von Ihnen eine E-Mail-Adresse sowie Informationen, welche uns die \u00dcberpr\u00fcfung gestatten, dass Sie der Inhaber der angegebenen E-Mail-Adresse sind und mit dem Empfang des Newsletters einverstanden sind. Weitere Daten werden nicht bzw. nur auf freiwilliger Basis erhoben. Diese Daten verwenden wir ausschlie\u00dflich f\u00fcr den Versand der angeforderten Informationen und geben diese nicht an Dritte weiter.\n\nDie Verarbeitung der in das Newsletteranmeldeformular eingegebenen Daten erfolgt ausschlie\u00dflich auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO). Die erteilte Einwilligung zur Speicherung der Daten, der E-Mail-Adresse sowie deren Nutzung zum Versand des Newsletters k\u00f6nnen Sie jederzeit widerrufen, etwa \u00fcber den \u201eAustragen\u201c-Link im Newsletter. Die Rechtm\u00e4\u00dfigkeit der bereits erfolgten Datenverarbeitungsvorg\u00e4nge bleibt vom Widerruf unber\u00fchrt.\n\nDie von Ihnen zum Zwecke des Newsletter-Bezugs bei uns hinterlegten Daten werden von uns bis zu Ihrer Austragung aus dem Newsletter gespeichert und nach der Abbestellung des Newsletters gel\u00f6scht. Daten, die zu anderen Zwecken bei uns gespeichert wurden bleiben hiervon unber\u00fchrt.',
              '***7. Plugins und Tools***',
              '**Vimeo**\n\nUnsere Website nutzt Plugins des Videoportals Vimeo. Anbieter ist die Vimeo Inc., 555 West 18th Street, New York, New York 10011, USA. Wenn Sie eine unserer mit einem Vimeo-Plugin ausgestatteten Seiten besuchen, wird eine Verbindung zu den Servern von Vimeo hergestellt. Dabei wird dem Vimeo-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Zudem erlangt Vimeo Ihre IP-Adresse. Dies gilt auch dann, wenn Sie nicht bei Vimeo eingeloggt sind oder keinen Account bei Vimeo besitzen. Die von Vimeo erfassten Informationen werden an den Vimeo-Server in den USA \u00fcbermittelt. Wenn Sie in Ihrem Vimeo-Account eingeloggt sind, erm\u00f6glichen Sie Vimeo, Ihr Surfverhalten direkt Ihrem pers\u00f6nlichen Profil zuzuordnen. Dies k\u00f6nnen Sie verhindern, indem Sie sich aus Ihrem Vimeo-Account ausloggen. Die Nutzung von Vimeo erfolgt im Interesse einer ansprechenden Darstellung unserer Online-Angebote. Dies stellt ein berechtigtes Interesse im Sinne des Art. 6 Abs. 1 lit. f DSGVO dar. Weitere Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerkl\u00e4rung von Vimeo unter: https://vimeo.com/privacy.',
              '***8. Eigene Dienste***',
              '**Bewerbungen**\n\nWir bieten Ihnen die M\u00f6glichkeit, sich bei uns zu bewerben (via Online-Bewerberformular). Im Folgenden informieren wir Sie \u00fcber Umfang, Zweck und Verwendung Ihrer im Rahmen des Bewerbungsprozesses erhobenen personenbezogenen Daten. Wir versichern, dass die Erhebung, Verarbeitung und Nutzung Ihrer Daten in \u00dcbereinstimmung mit geltendem Datenschutzrecht und allen weiteren gesetzlichen Bestimmungen erfolgt und Ihre Daten streng vertraulich behandelt werden.',
              '\u2014 Umfang und Zweck der Datenerhebung\n\nWenn Sie uns eine Bewerbung zukommen lassen, verarbeiten wir Ihre damit verbundenen personenbezogenen Daten (z. B. Kontakt- und Kommunikationsdaten, Bewerbungsunterlagen, Notizen im Rahmen von Bewerbungsgespr\u00e4chen etc.), soweit dies zur Entscheidung \u00fcber die Begr\u00fcndung eines Besch\u00e4ftigungsverh\u00e4ltnisses erforderlich ist. Rechtsgrundlage hierf\u00fcr ist \u00a7 26 BDSG-neu nach deutschem Recht (Anbahnung eines Besch\u00e4ftigungsverh\u00e4ltnisses), Art. 6 Abs. 1 lit. b DSGVO (allgemeine Vertragsanbahnung) und \u2013 sofern Sie eine Einwilligung erteilt haben \u2013 Art. 6 Abs. 1 lit. a DSGVO. Die Einwilligung ist jederzeit widerrufbar. Ihre personenbezogenen Daten werden innerhalb unseres Unternehmens ausschlie\u00dflich an Personen weitergegeben, die an der Bearbeitung Ihrer Bewerbung beteiligt sind.',
              'Sofern die Bewerbung erfolgreich ist, werden die von Ihnen eingereichten Daten auf Grundlage von \u00a7 26 BDSG-neu und Art. 6 Abs. 1 lit. b DSGVO zum Zwecke der Durchf\u00fchrung des Besch\u00e4ftigungsverh\u00e4ltnisses in unseren Datenverarbeitungssystemen gespeichert.',
              '\u2014 Aufbewahrungsdauer der Daten\n\nWenn wir Ihnen kein Stellenangebot machen k\u00f6nnen, Sie ein Stellenangebot ablehnen, Ihre Bewerbung zur\u00fcckziehen, Ihre Einwilligung zur Datenverarbeitung widerrufen oder uns zur L\u00f6schung der Daten auffordern, werden die von Ihnen \u00fcbermittelten Daten inkl. ggf. verbleibender physischer Bewerbungsunterlagen f\u00fcr maximal 6 Monate nach Abschluss des Bewerbungsverfahrens gespeichert bzw. aufbewahrt (Aufbewahrungsfrist), um die Einzelheiten des Bewerbungsprozesses im Falle von Unstimmigkeiten nachvollziehen zu k\u00f6nnen (Art. 6 Abs. 1 lit. f DSGVO).',
              'DIESER SPEICHERUNG K\u00d6NNEN SIE WIDERSPRECHEN, SOFERN IHRERSEITS BERECHTIGTE INTERESSEN VORLIEGEN, DIE UNSERE INTERESSEN \u00dcBERWIEGEN.',
              'Nach Ablauf der Aufbewahrungsfrist werden die Daten gel\u00f6scht, sofern keine gesetzliche Aufbewahrungspflicht oder ein sonstiger Rechtsgrund zur weiteren Speicherung vorliegt. Sofern ersichtlich ist, dass die Aufbewahrung Ihrer Daten nach Ablauf der Aufbewahrungsfrist erforderlich sein wird (z. B. aufgrund eines drohenden oder anh\u00e4ngigen Rechtsstreits), findet eine L\u00f6schung erst statt, wenn die Daten gegenstandslos geworden sind. Sonstige gesetzliche Aufbewahrungspflichten bleiben unber\u00fchrt.',
            ],
          };
          dispatch(setProtectionData({ userLanguage, data: mockData }));
        }

        // TODO: commented for temp deploy
        // console.error('Fetching error:', error);
        // setError(error);
      })
      .finally(() => {
        setLoading(false);
        clearTimeout(timeout);
      });
  }, [userLanguage]);

  if (loading) return <LoadingPage />;
  if (error || !protectionData) return <ErrorPage />;

  return (
    <>
      <Box
        component="section"
        className="px-[48px] flex flex-col justify-start items-center"
        sx={{
          gap: { xs: '24px', md: '48px' },
          py: { xs: '55px', md: '110px' },
        }}
      >
        <Box
          className="max-w-[1280px] w-full flex justify-start items-start"
          sx={{
            padding: { xs: '64px 56px 46px 0px', md: '120px 56px 46px 0px' },
          }}
        >
          <Typography
            sx={{
              fontSize: { xs: '50px', md: '80px' },
              fontWeight: '400',
              lineHeight: 'normal',
            }}
          >
            {protectionData.title}
          </Typography>
        </Box>

        <Box
          className="max-w-[1280px] w-full flex flex-col"
          sx={{
            gap: { xs: '16px', md: '32px' },
          }}
        >
          {protectionData.text_blocks.map((markdownString, idx) => (
            <Box key={idx} className="text-left">
              <ReactMarkdown children={markdownString} components={renderers} />
            </Box>
          ))}
        </Box>
      </Box>
    </>
  );
}

export default Datenschutz;
